//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZlPos.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class R {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal R() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZlPos.Resources.R", typeof(R).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 中仑零售 的本地化字符串。
        /// </summary>
        internal static string app_name {
            get {
                return ResourceManager.GetString("app_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保鲜袋 的本地化字符串。
        /// </summary>
        internal static string bags {
            get {
                return ResourceManager.GetString("bags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 余额： 的本地化字符串。
        /// </summary>
        internal static string balance {
            get {
                return ResourceManager.GetString("balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 门店名称： 的本地化字符串。
        /// </summary>
        internal static string branch_name {
            get {
                return ResourceManager.GetString("branch_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日期范围： 的本地化字符串。
        /// </summary>
        internal static string date_time {
            get {
                return ResourceManager.GetString("date_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 铁丝挂钩 的本地化字符串。
        /// </summary>
        internal static string hook {
            get {
                return ResourceManager.GetString("hook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 积分： 的本地化字符串。
        /// </summary>
        internal static string integral {
            get {
                return ResourceManager.GetString("integral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 会员号： 的本地化字符串。
        /// </summary>
        internal static string member_code {
            get {
                return ResourceManager.GetString("member_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 会员： 的本地化字符串。
        /// </summary>
        internal static string member_name {
            get {
                return ResourceManager.GetString("member_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 金额 的本地化字符串。
        /// </summary>
        internal static string money {
            get {
                return ResourceManager.GetString("money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数量 的本地化字符串。
        /// </summary>
        internal static string mumber {
            get {
                return ResourceManager.GetString("mumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 品名;数量;单价;金额 的本地化字符串。
        /// </summary>
        internal static string note_title {
            get {
                return ResourceManager.GetString("note_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 支付方式 的本地化字符串。
        /// </summary>
        internal static string payType {
            get {
                return ResourceManager.GetString("payType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 充值： 的本地化字符串。
        /// </summary>
        internal static string rechargeamount {
            get {
                return ResourceManager.GetString("rechargeamount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退货额： 的本地化字符串。
        /// </summary>
        internal static string returnamount {
            get {
                return ResourceManager.GetString("returnamount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退货数： 的本地化字符串。
        /// </summary>
        internal static string returnnums {
            get {
                return ResourceManager.GetString("returnnums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收银员： 的本地化字符串。
        /// </summary>
        internal static string shop_cashier_num {
            get {
                return ResourceManager.GetString("shop_cashier_num", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找零： 的本地化字符串。
        /// </summary>
        internal static string shop_change {
            get {
                return ResourceManager.GetString("shop_change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地址：江苏省宁波市东昌路12号 的本地化字符串。
        /// </summary>
        internal static string shop_company_address {
            get {
                return ResourceManager.GetString("shop_company_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公司名称：江苏一五一十家居用品有限公司 的本地化字符串。
        /// </summary>
        internal static string shop_company_name {
            get {
                return ResourceManager.GetString("shop_company_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公司网址： 的本地化字符串。
        /// </summary>
        internal static string shop_company_site {
            get {
                return ResourceManager.GetString("shop_company_site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电话： 的本地化字符串。
        /// </summary>
        internal static string shop_company_tel {
            get {
                return ResourceManager.GetString("shop_company_tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 宁波月湖店 的本地化字符串。
        /// </summary>
        internal static string shop_company_title {
            get {
                return ResourceManager.GetString("shop_company_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Demo 版本！ 的本地化字符串。
        /// </summary>
        internal static string shop_demo {
            get {
                return ResourceManager.GetString("shop_demo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 原价： 的本地化字符串。
        /// </summary>
        internal static string shop_goods_buy_total_price {
            get {
                return ResourceManager.GetString("shop_goods_buy_total_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数量： 的本地化字符串。
        /// </summary>
        internal static string shop_goods_number {
            get {
                return ResourceManager.GetString("shop_goods_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实收： 的本地化字符串。
        /// </summary>
        internal static string shop_goods_sale_total_collection {
            get {
                return ResourceManager.GetString("shop_goods_sale_total_collection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 现价： 的本地化字符串。
        /// </summary>
        internal static string shop_goods_sale_total_price {
            get {
                return ResourceManager.GetString("shop_goods_sale_total_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 优惠： 的本地化字符串。
        /// </summary>
        internal static string shop_goods_youhui {
            get {
                return ResourceManager.GetString("shop_goods_youhui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单据号： 的本地化字符串。
        /// </summary>
        internal static string shop_note_num {
            get {
                return ResourceManager.GetString("shop_note_num", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 门店号： 的本地化字符串。
        /// </summary>
        internal static string shop_num {
            get {
                return ResourceManager.GetString("shop_num", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 付款： 的本地化字符串。
        /// </summary>
        internal static string shop_payment {
            get {
                return ResourceManager.GetString("shop_payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打印时间： 的本地化字符串。
        /// </summary>
        internal static string shop_print_time {
            get {
                return ResourceManager.GetString("shop_print_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单据日期： 的本地化字符串。
        /// </summary>
        internal static string shop_receipt_date {
            get {
                return ResourceManager.GetString("shop_receipt_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单号: 的本地化字符串。
        /// </summary>
        internal static string shop_receipt_num {
            get {
                return ResourceManager.GetString("shop_receipt_num", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务专线： 的本地化字符串。
        /// </summary>
        internal static string shop_Service_Line {
            get {
                return ResourceManager.GetString("shop_Service_Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 谢谢惠顾,欢迎再次光临！ 的本地化字符串。
        /// </summary>
        internal static string shop_thanks {
            get {
                return ResourceManager.GetString("shop_thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 合计： 的本地化字符串。
        /// </summary>
        internal static string subtotal {
            get {
                return ResourceManager.GetString("subtotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 交易额： 的本地化字符串。
        /// </summary>
        internal static string ticketamount {
            get {
                return ResourceManager.GetString("ticketamount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 交易数： 的本地化字符串。
        /// </summary>
        internal static string ticketnums {
            get {
                return ResourceManager.GetString("ticketnums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间： 的本地化字符串。
        /// </summary>
        internal static string time {
            get {
                return ResourceManager.GetString("time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收银对账 的本地化字符串。
        /// </summary>
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 雨伞 的本地化字符串。
        /// </summary>
        internal static string umbrella {
            get {
                return ResourceManager.GetString("umbrella", resourceCulture);
            }
        }
    }
}
